name: Auto Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Docker Build & Push
      run: |
        docker build -t crpi-dcf0z79gs3awh4x6.cn-hangzhou.personal.cr.aliyuncs.com/sanmao666/sanmao666:${{ github.sha }} .
        docker login -u ${{ secrets.ACR_USER }} -p ${{ secrets.ACR_PASSWORD }} crpi-dcf0z79gs3awh4x6.cn-hangzhou.personal.cr.aliyuncs.com
        docker push crpi-dcf0z79gs3awh4x6.cn-hangzhou.personal.cr.aliyuncs.com/sanmao666/sanmao666:${{ github.sha }}

    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: root
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull crpi-dcf0z79gs3awh4x6.cn-hangzhou.personal.cr.aliyuncs.com/sanmao666/sanmao666:${{ github.sha }}
          docker stop zhengshu || true
          docker rm zhengshu || true
          docker run -d --name zhengshu -p 5321:5321 \
            crpi-dcf0z79gs3awh4x6.cn-hangzhou.personal.cr.aliyuncs.com/sanmao666/sanmao666:${{ github.sha }}
