name: Auto Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      REGISTRY: crpi-dcf0z79gs3awh4x6.cn-hangzhou.personal.cr.aliyuncs.com
      IMAGE: sanmao666/sanmao666
      TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login & Build
        run: |
          # 安全登录（先登录后构建）
          echo "${{ secrets.ACR_PASSWORD }}" | docker login \
            --username ${{ secrets.ACR_USER }} \
            --password-stdin $REGISTRY
          
          # 构建并推送镜像
          docker build -t $REGISTRY/$IMAGE:$TAG .
          docker push $REGISTRY/$IMAGE:$TAG

      - name: SSH Deployment
        uses: appleboy/ssh-action@v1.2.0  # 升级到最新版
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root  # 根据实际情况修改
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_timeout: 5m
          envs: "REGISTRY,IMAGE,TAG"  # 传递环境变量
          script: |
            # 调试命令
            echo "=== 连接测试 ==="
            whoami
            pwd
            
            echo "=== 开始部署 ==="
            docker pull $REGISTRY/$IMAGE:$TAG
            docker stop zhengshu || true
            docker rm zhengshu || true
            docker run -d \
              --name zhengshu \
              -p 5321:5321 \
              -v /app/data:/app/data \
              $REGISTRY/$IMAGE:$TAG
